name: Build
on:
  release:
    types: [published]
env:
  GHC: '8.10.4'
jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Setup
        run: |
          apk update
          apk add \
            git sudo curl \
            gcc g++ make ncurses-dev \
            gmp-dev binutils-gold \
            openssl-dev openssl-libs-static \
            bzip2 bzip2-dev bzip2-static \
            zlib zlib-dev zlib-static \
            ncurses ncurses-dev ncurses-static \
            bash
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ env.GHC }}
      - uses: actions/checkout@v2
      - name: Build static binary
        run: bash build.sh
        env:
          STATIC_BUILD: HELLYEAH
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/hellsmack
          asset_name: hellsmack-${{ runner.os }}
          asset_content_type: application/octet-stream
  nonlinux:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ env.GHC }}
      - if: runner.os == 'Windows'
        name: Setup Cabal native lib dirs
        run: |
          cabal user-config update -a "extra-include-dirs: C:/msys64/mingw64/include" -a "extra-lib-dirs: C:/msys64/mingw64/lib"
      - name: Build binary
        run: bash build.sh
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/hellsmack
          asset_name: hellsmack-${{ runner.os }}
          asset_content_type: application/octet-stream
