name: Build binaries
on:
  release:
    types: [published]
defaults:
  run:
    shell: bash
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            targetOs: Linux
          - os: ubuntu-latest
            targetOs: Windows
          - os: macos-latest
            targetOs: macOS
    name: Build binary for ${{ matrix.targetOs }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16
        with:
          install_url: https://releases.nixos.org/nix/nix-2.5.1/install
          extra_nix_config: |
            accept-flake-config = true
      - name: Build binary
        # see https://github.com/NixOS/nix/issues/5302
        run: nix build .\?rev=$(git rev-parse HEAD)#binaries-${{ matrix.targetOS }}
      - name: Prepare upload
        run: |
          cd result/bin
          7z a -l ${{ github.workspace }}/hellsmack.zip .
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: hellsmack.zip
          asset_name: hellsmack-${{ matrix.targetOs }}.zip
          asset_content_type: application/zip
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    name: Test built binaries
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - name: Download and extract binary
        run: |
          curl -sL https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/hellsmack-${{ runner.os }}.zip > hellsmack.zip
          7z e hellsmack.zip
      - name: Basic functionality tests
        run: |
          ./hellsmack --version
