name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            accept-flake-config = true
      - uses: cachix/cachix-action@v10
        with:
          name: hellsmack
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build and test
        run: nix flake check --option sandbox false
      - name: Run docspec
        run: nix develop --command sh -c 'cabal build --enable-tests && ./docspec.sh'
