name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrkkrp/ormolu-action@v5
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            substituters = https://cache.nixos.org https://hydra.iohk.io
      - uses: cachix/cachix-action@v10
        with:
          name: hellsmack
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Setup cabal-docspec
        run: |
          CABAL_DIR=~/.cabal/bin
          echo "$CABAL_DIR" >> $GITHUB_PATH
          DOCSPEC="$CABAL_DIR/cabal-docspec"
          mkdir -p "$CABAL_DIR"
          curl -sL https://github.com/phadej/cabal-extras/releases/download/cabal-docspec-$CABAL_DOCSPEC_VERSION/cabal-docspec-$CABAL_DOCSPEC_VERSION.xz | xz -d > "$DOCSPEC"
          chmod +x "$DOCSPEC"
          "$DOCSPEC" --version
        env:
          CABAL_DOCSPEC_VERSION: '0.0.0.20210111'

      - name: Build and test
        run: nix-build --option sandbox false
      - name: Run docspec
        run: nix-shell --command 'cabal build --enable-tests && ./docspec.sh'
