name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            substituters = https://cache.nixos.org https://hydra.iohk.io
      - uses: cachix/cachix-action@v10
        with:
          name: hellsmack
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build and test
        run: nix flake check --option sandbox false
      - name: Run docspec
        run: nix develop --command sh -c 'cabal build --enable-tests && ./docspec.sh'
