name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16
        with:
          install_url: https://releases.nixos.org/nix/nix-2.5.1/install
          extra_nix_config: |
            accept-flake-config = true
      - uses: cachix/cachix-action@v10
        with:
          name: hellsmack
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Ugly hack
        # see https://github.com/input-output-hk/haskell.nix/issues/1097
        run: sed -i 's/ "x86_64-darwin"//g' flake.nix
      - name: Build and test
        run: nix flake check --option sandbox false
      - name: Run docspec
        run: nix develop --command sh -c 'cabal build --enable-tests && ./docspec.sh'
